### ISSUE TITLE
Mac: Freetype not found

### ISSUE THREAD

**Issue by timkaechele** [coderdojoka/py2cd#2]
Pygame doesn't handle the pygame.freetype module correctly, though it is properly installed. 

I was able to reproduce the bug on my Mac with Homebrew, Pygame and Python 3

**Comment by mk1012** [comment]
Kannst du mal probieren `pygame.font`zu importieren anstatt pygame.freetype? Die beiden sind austauschbar, freetype wäre wahrscheinlich besser, aber vielleicht geht ja pygame.font?
